### PR TITLE
Fix VPC parser

### PR DESCRIPTION
**Pull request by ddiachkov**
This PR fixes problems with VPC parser + adds `cidr_block_association_set` attribute to model.
https://github.com/fog/fog-aws/issues/379 was not sufficient – VPC list still contains duplicates with invalid status.

**NB:** `cidr_block_association_set` and `ipv_6_cidr_block_association_set` are array of hashes (currently `ipv_6_cidr_block_association_set` is a Hash)

### CODE REVIEW

File: lib/fog/aws/models/compute/vpc.rb [hunk 1]
```diff
@@ -10,8 +10,11 @@ class VPC < Fog::Model
         attribute :tags,             :aliases => 'tagSet'
         attribute :tenancy,          :aliases => 'instanceTenancy'
         attribute :is_default,       :aliases => 'isDefault'
-        attribute :ipv_6_cidr_block_association_set,  :aliases => 'ipv6CidrBlockAssociationSet'
-        attribute :amazon_provided_ipv_6_cidr_block,  :aliases => 'amazonProvidedIpv6CidrBlock'
+
+        attribute :cidr_block_association_set, :aliases => 'cidrBlockAssociationSet'
+
+        attribute :ipv_6_cidr_block_association_set, :aliases => 'ipv6CidrBlockAssociationSet'
```
Comment (geemus) [inline lib/fog/aws/models/compute/vpc.rb]: I guess it was already there, but it seems surprising to me that this is `ipv_6_cidr_block_association_set` instead of `ipv6_cidr_block_association_set`. Does that make sense? I just happened to notice here (and have the same question about the new attribute below). What do you think?

File: lib/fog/aws/parsers/compute/describe_vpcs.rb [hunk 2]
```diff
@@ -4,55 +4,89 @@ module Compute
...
+                @current_tag_value = value
+
+              # cidrBlockAssociationSet
+
+              when 'vpcSet.item.cidrBlockAssociationSet.item.cidrBlock',
+                   'vpcSet.item.cidrBlockAssociationSet.item.associationId'
+                @current_cidr_block[name] = value
+
+              when 'vpcSet.item.cidrBlockAssociationSet.item.cidrBlockState'
+                @current_cidr_block['state'] = value.squish
```
Comment (geemus) [inline lib/fog/aws/parsers/compute/describe_vpcs.rb]: In the old version `state` was capitalized as `State`, not sure it makes that much difference, but probably better safe than sorry. Could you change it?

File: lib/fog/aws/parsers/compute/describe_vpcs.rb [hunk 3]
```diff
@@ -4,55 +4,89 @@ module Compute
...
+                @current_vpc['cidrBlockAssociationSet'] << @current_cidr_block
+
+              # ipv6CidrBlockAssociationSet
+
+              when 'vpcSet.item.ipv6CidrBlockAssociationSet.item.ipv6CidrBlock',
+                   'vpcSet.item.ipv6CidrBlockAssociationSet.item.associationId'
+                @current_ipv6_block[name] = value
+
+              when 'vpcSet.item.ipv6CidrBlockAssociationSet.item.ipv6CidrBlockState'
+                @current_ipv6_block['state'] = value.squish
```
Comment (geemus) [inline lib/fog/aws/parsers/compute/describe_vpcs.rb]: Same thing here, if we could keep it as `State` for safety that would be great.

**Comment by geemus** [comment]
@lanej This looks good to me other than my feedback, but I would appreciate an extra set of eyes if you have a chance. Thanks!

File: lib/fog/aws/models/compute/vpc.rb (hunk 1 above)
Comment (ddiachkov) [reply lib/fog/aws/models/compute/vpc.rb]: I think you are right. We could just add alias for backward compatibility (ipv_6_cidr_block_association_set is already released...)

File: lib/fog/aws/parsers/compute/describe_vpcs.rb (hunk 2 above)
Comment (geemus) [reply lib/fog/aws/parsers/compute/describe_vpcs.rb]: I don't feel super strongly about it, so I'm alright leaving it as you suggest. I just wanted to at least discuss it, which we now have. Thanks!

File: lib/fog/aws/models/compute/vpc.rb (hunk 1 above)
Comment (geemus) [reply lib/fog/aws/models/compute/vpc.rb]: I hadn't even thought about that, but that sounds good. That way we can have more consistent names, but avoid breaking anybody. Sound good?

**Comment by lanej** [comment]
Seeing some failure when doing live testing

```
irb(main):003:0> aws.describe_vpcs
#<NoMethodError: undefined method `squish' for "associated\n                    ":String>
#<NoMethodError: undefined method `squish' for "associated\n                    \n                ":String>
#<NoMethodError: undefined method `squish' for #<String:0x007fdf881e4898>>
#<NoMethodError: undefined method `squish' for "false\n        ":String>
#<NoMethodError: undefined method `squish' for "true\n        \n    ":String>
#<NoMethodError: undefined method `squish' for "true\n        \n    \n":String>
```

[String#squish](http://api.rubyonrails.org/classes/String.html#method-i-squish) is an rails-ism that we do not have access to.

**Comment by geemus** [comment]
I'm fine with this going in and adding the aliases later too, if that is easier.

**Comment by lanej** [comment]
A `squish` reference was mistakenly introduced in https://github.com/fog/fog-aws/commit/9e97b414af1d2345f3cf02a7cac798e737fdb07a.  

@ddiachkov please rebase this PR and resolve conflicts, when you're ready.

**Comment by ddiachkov** [comment]
@lanej done

**Comment by lanej** [comment]
Live tests result:

```
» FOG_MOCK=false be shindo tests/requests/compute/vpc_tests.rb
[fog][WARNING] Setting default fog timeout to 2000 seconds

```
  Fog::Compute[:aws] | vpc requests (aws)
    success
      #create_vpc + has proper format
      #create_vpc + has proper format
      #describe_vpcs - has proper format
        {"vpcSet"=>[{"tagSet"=>{}, "ipv6CidrBlockAssociationSet"=>{}, "vpcId"=>"vpc-9ee916e6", "state"=>"associated", "cidrBlock"=>"10.255.254.0/28"}, {"tagSet"=>{}, "ipv6CidrBlockAssociationSet"=>{}, "dhcpOptionsId"=>"dopt-d04fd7b4", "instanceTenancy"=>"default", "isDefault"=>false}, {"tagSet"=>{}, "ipv6CidrBlockAssociationSet"=>{}, "vpcId"=>"vpc-44ed123c", "state"=>"associated", "cidrBlock"=>"10.255.254.0/28"}, {"tagSet"=>{}, "ipv6CidrBlockAssociationSet"=>{}, "dhcpOptionsId"=>"dopt-d04fd7b4", "instanceTenancy"=>"default", "isDefault"=>false}], "requestId"=>"9a9e14cd-ccd0-4a07-bcd5-674e5a34de41"} does not match {"vpcSet"=>[{"vpcId"=>String, "state"=>String, "cidrBlock"=>String, "dhcpOptionsId"=>String, "tagSet"=>Hash, "instanceTenancy"=>Fog::Nullable::String}], "requestId"=>String}
```

Beyond that, I think this is ready to go.

**Comment by lanej** [comment]
@geemus I am still getting `nil` VPC ids with this change :(.

**Comment by ddiachkov** [comment]
@lanej thats not right... Which field contains `nil`?

**Comment by lanej** [comment]
```
                  <Fog::Compute::AWS::VPC
        id=nil,
        state=nil,
        cidr_block=nil,
        dhcp_options_id="dopt-d04fd7b4",
        tags={},
        tenancy="default",
        is_default=false,
        ipv_6_cidr_block_association_set={},
        amazon_provided_ipv_6_cidr_block=false
      >
```

**Comment by ddiachkov** [comment]
Let me check it on a real AWS

**Comment by ddiachkov** [comment]
Hey @lanej, are you sure you use this branch?

```ruby
  [{"tagSet"=>{},
    "cidrBlockAssociationSet"=>
     [{"cidrBlock"=>"10.255.254.0/28",
       "associationId"=>"vpc-cidr-assoc-687a8b02",
       "state"=>"associated"}],
    "ipv6CidrBlockAssociationSet"=>[],
    "vpcId"=>"vpc-cab34db2",
    "state"=>"available",
    "cidrBlock"=>"10.255.254.0/28",
    "dhcpOptionsId"=>"dopt-2873c74c",
    "instanceTenancy"=>"default",
    "isDefault"=>false},
   {"tagSet"=>{},
    "cidrBlockAssociationSet"=>
     [{"cidrBlock"=>"172.31.0.0/16",
       "associationId"=>"vpc-cidr-assoc-473c8e2e",
       "state"=>"associated"}],
    "ipv6CidrBlockAssociationSet"=>[],
    "vpcId"=>"vpc-3e9d1659",
    "state"=>"available",
    "cidrBlock"=>"172.31.0.0/16",
    "dhcpOptionsId"=>"dopt-2873c74c",
    "instanceTenancy"=>"default",
    "isDefault"=>true},
   {"tagSet"=>{},
    "cidrBlockAssociationSet"=>
     [{"cidrBlock"=>"10.255.254.0/28",
       "associationId"=>"vpc-cidr-assoc-c17988ab",
       "state"=>"associated"}],
    "ipv6CidrBlockAssociationSet"=>[],
    "vpcId"=>"vpc-5cb04e24",
    "state"=>"available",
    "cidrBlock"=>"10.255.254.0/28",
    "dhcpOptionsId"=>"dopt-2873c74c",
    "instanceTenancy"=>"default",
    "isDefault"=>false}],
 "requestId"=>"920616e6-36fd-4779-9c41-21f0518aa52c"}
```

Thats what I get on a real AWS. Notice that ipv_6_cidr_block_association_set is an Array, not Hash.

**Comment by ddiachkov** [comment]
I've added additional format tests.

**Comment by lanej** [comment]
Thanks @ddiachkov.

Hey @geemus, how would you feel about moving the `Gemfile.edge` tests to allowed failures in Travis CI?  This branch is failing due to an unrelated change on `fog-core`, I think https://github.com/fog/fog-core/pull/218

**Comment by geemus** [comment]
@lanej feel free to do that if you think it makes sense (though presumably we'll want to also fix that before release?).

**Comment by lanej** [comment]
@ddiachkov sorry for the delay.  If you rebase off master, we can get this out.

**Comment by ddiachkov** [comment]
No worries. I've rebased the code – looks like tests are passed.

**Comment by lanej** [comment]
@geemus has your feedback been addressed?

**Comment by geemus** [comment]
@lanej I think so, thanks for double checking!

**Comment by geemus** [comment]
@ddiachkov thanks!
